name: 🚩 Bugs, Errors, and Other Issues
description: Report an issue for userChrome Companion
labels:
  - "bug"
  - "issue"
body:
  - type: markdown
    attributes:
      value: |
        ### Before submitting, Please go through the checklist below.

  - type: checkboxes
    id: confirmations
    attributes:
      label: "My Checklist:"
      description: "Verification Checklist template"
      options:
        - label: "a verification that needs to be checked"
          required: true
        - label: "a verification that doesn't need to be checked"

  - type: textarea
    id: issue-description
    attributes:
      label: "The Issue:"
      description: "A detailed description of the issue, bug, or report"
      placeholder: "A detailed description of the issue, bug, or report"
    validations:
      required: true

  - type: textarea
    id: picture-video
    attributes:
      label: "Picture/Video of the Issue:"
      description: "Screenshot(s) or video of the issue are preferred."
      placeholder: "Drag & Drop | Copy & Paste | or Link to Picture & Video"
    validations:
      required: false
