name: 🆕 Features, Suggestions, & Request
description: Suggest, request, or contribute features, improvements or modifications to this project.
title: "[Feature Request] "
labels:
  - "enhancement"
  - "issue"
body:
  - type: markdown
    attributes:
      value: |
        ## Suggest, request, or contribute features, improvements or modifications to this project.

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Please confirm (not required):"
      options:
        - label: "I can, or want to, contribute to this development."

  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the Feature | Suggestion | Request:"
      placeholder: "A detailed description of the Feature / Suggestion / Modification"
    validations:
      required: true

  - type: textarea
    id: picture-video
    attributes:
      label: "Picture/Video of the desired outcome (if applicable) (not required):"
      placeholder: "Drag & Drop | Copy & Paste | or Link to Picture & Video"
    validations:
      required: false
